// Code generated by Slice Machine. DO NOT EDIT.

import Hero from "./Hero/index.svelte";
import Programs from "./Programs/index.svelte";
import RichText from "./RichText/index.svelte";
import ShowCase from "./ShowCase/index.svelte";
import Staff from "./Staff/index.svelte";
import Videos from "./Videos/index.svelte";
import WatchVideo from "./WatchVideo/index.svelte";
import WordList from "./WordList/index.svelte";

export const components = {
  hero: Hero,
  programs: Programs,
  rich_text: RichText,
  show_case: ShowCase,
  staff: Staff,
  videos: Videos,
  watch_video: WatchVideo,
  word_list: WordList,
};
