// Code generated by Slice Machine. DO NOT EDIT.

import Hero from "./Hero/index.svelte";
import RichText from "./RichText/index.svelte";
import Staff from "./Staff/index.svelte";
import WordList from "./WordList/index.svelte";

export const components = {
  hero: Hero,
  rich_text: RichText,
  staff: Staff,
  word_list: WordList,
};
