// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };
type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

<<<<<<< HEAD
type PageDocumentDataSlicesSlice =
  | ProgramsSlice
  | ShowCaseSlice
  | StaffSlice
  | WordListSlice
  | HeroSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Program → Box*
 */
export interface ProgramDocumentDataBoxItem {
  /**
   * Title field in *Program → Box*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program.box[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *Program → Box*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program.box[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *Program → Box*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: program.box[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content Link field in *Program → Box*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: program.box[].content_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  content_link: prismic.ContentRelationshipField;

  /**
   * Width field in *Program → Box*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: program.box[].width
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  width: prismic.SelectField<"Small" | "Medium" | "Large" | "XL">;

  /**
   * Height field in *Program → Box*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: program.box[].height
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  height: prismic.SelectField<"Small" | "Medium" | "Large" | "XL">;
}

type ProgramDocumentDataSlicesSlice = HeroSlice | ProgramsSlice | RichTextSlice;

/**
 * Content for Program documents
 */
interface ProgramDocumentData {
  /**
   * Program Title field in *Program*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program.program_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  program_title: prismic.RichTextField;

  /**
   * Program Tagline field in *Program*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program.program_tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  program_tagline: prismic.KeyTextField;

  /**
   * Program Image field in *Program*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: program.program_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  program_image: prismic.ImageField<never>;

  /**
   * Box field in *Program*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: program.box[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  box: prismic.GroupField<Simplify<ProgramDocumentDataBoxItem>>;

  /**
   * Slice Zone field in *Program*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: program.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProgramDocumentDataSlicesSlice> /**
   * Meta Title field in *Program*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: program.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Program*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: program.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Program*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: program.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Program document from Prismic
 *
 * - **API ID**: `program`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProgramDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProgramDocumentData>,
    "program",
    Lang
  >;

/**
 * Item in *ProgramMenu → Navigation*
 */
export interface ProgrammenuDocumentDataNavigationItem {
  /**
   * Navigation Link field in *ProgramMenu → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: programmenu.navigation[].navigation_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navigation_link: prismic.LinkField;

  /**
   * Navigation Label field in *ProgramMenu → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: programmenu.navigation[].navigation_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  navigation_label: prismic.KeyTextField;

  /**
   * Sub Menu field in *ProgramMenu → Navigation*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: programmenu.navigation[].sub_menu
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sub_menu: prismic.ContentRelationshipField;
}

/**
 * Content for ProgramMenu documents
 */
interface ProgrammenuDocumentData {
  /**
   * Program Title field in *ProgramMenu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: programmenu.program_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  program_title: prismic.KeyTextField;

  /**
   * Navigation field in *ProgramMenu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: programmenu.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<
    Simplify<ProgrammenuDocumentDataNavigationItem>
  >;
}

/**
 * ProgramMenu document from Prismic
 *
 * - **API ID**: `programmenu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProgrammenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProgrammenuDocumentData>,
    "programmenu",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Navigation Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].navigation_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navigation_link: prismic.LinkField;

  /**
   * Navigation Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].navigation_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  navigation_label: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type VideoDocumentDataSlicesSlice = WatchVideoSlice;

<<<<<<< HEAD
/**
 * Content for Video documents
 */
interface VideoDocumentData {
  /**
   * Title field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Video*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: video.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<VideoDocumentDataSlicesSlice> /**
   * Meta Title field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: video.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: video.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Video*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Video document from Prismic
 *
 * - **API ID**: `video`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<VideoDocumentData>, "video", Lang>;

type VideoindexDocumentDataSlicesSlice = VideosSlice;

/**
 * Content for VideoIndex documents
 */
interface VideoindexDocumentData {
  /**
   * Title field in *VideoIndex*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: videoindex.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *VideoIndex*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: videoindex.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField;

  /**
   * Slice Zone field in *VideoIndex*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: videoindex.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<VideoindexDocumentDataSlicesSlice> /**
   * Meta Title field in *VideoIndex*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: videoindex.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *VideoIndex*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: videoindex.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *VideoIndex*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: videoindex.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * VideoIndex document from Prismic
 *
 * - **API ID**: `videoindex`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideoindexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<VideoindexDocumentData>,
    "videoindex",
    Lang
  >;

export type AllDocumentTypes =
  | PageDocument
  | ProgramDocument
  | ProgrammenuDocument
  | SettingsDocument
  | VideoDocument
  | VideoindexDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: H1 italics for gold
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Hero Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * CTA Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_button_link: prismic.LinkField;

  /**
   * CTA Button Label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_button_label: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Programs → Default → Primary → Programs*
 */
export interface ProgramsSliceDefaultPrimaryProgramsItem {
  /**
   * Program field in *Programs → Default → Primary → Programs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: programs.default.primary.programs[].program
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  program: prismic.ContentRelationshipField<"program">;
}

/**
 * Primary content in *Programs → Default → Primary*
 */
export interface ProgramsSliceDefaultPrimary {
  /**
   * Programs field in *Programs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: programs.default.primary.programs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  programs: prismic.GroupField<
    Simplify<ProgramsSliceDefaultPrimaryProgramsItem>
  >;
}

/**
 * Default variation for Programs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProgramsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProgramsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Programs*
 */
type ProgramsSliceVariation = ProgramsSliceDefault;

/**
 * Programs Shared Slice
 *
 * - **API ID**: `programs`
 * - **Description**: Programs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProgramsSlice = prismic.SharedSlice<
  "programs",
  ProgramsSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *ShowCase → Default → Primary → Show PIece*
 */
export interface ShowCaseSliceDefaultPrimaryShowPieceItem {
  /**
   * Image field in *ShowCase → Default → Primary → Show PIece*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: show_case.default.primary.show_piece[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ShowCase → Default → Primary → Show PIece*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: show_case.default.primary.show_piece[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * body field in *ShowCase → Default → Primary → Show PIece*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: show_case.default.primary.show_piece[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * LInk field in *ShowCase → Default → Primary → Show PIece*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: show_case.default.primary.show_piece[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Reverse field in *ShowCase → Default → Primary → Show PIece*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: show_case.default.primary.show_piece[].reverse
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  reverse: prismic.BooleanField;
}

/**
 * Primary content in *ShowCase → Default → Primary*
 */
export interface ShowCaseSliceDefaultPrimary {
  /**
   * Heading field in *ShowCase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: show_case.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *ShowCase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: show_case.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Show PIece field in *ShowCase → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: show_case.default.primary.show_piece[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  show_piece: prismic.GroupField<
    Simplify<ShowCaseSliceDefaultPrimaryShowPieceItem>
  >;
}

/**
 * Default variation for ShowCase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShowCaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ShowCaseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ShowCase*
 */
type ShowCaseSliceVariation = ShowCaseSliceDefault;

/**
 * ShowCase Shared Slice
 *
 * - **API ID**: `show_case`
 * - **Description**: ShowCase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShowCaseSlice = prismic.SharedSlice<
  "show_case",
  ShowCaseSliceVariation
>;

/**
 * Item in *Staff → Default → Primary → Staff Info*
 */
export interface StaffSliceDefaultPrimaryStaffInfoItem {
  /**
   * Avatar field in *Staff → Default → Primary → Staff Info*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: staff.default.primary.staff_info[].avatar
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Name field in *Staff → Default → Primary → Staff Info*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: staff.default.primary.staff_info[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *Staff → Default → Primary → Staff Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: staff.default.primary.staff_info[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Staff → Default → Primary*
 */
export interface StaffSliceDefaultPrimary {
  /**
   * Heading field in *Staff → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: staff.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Staff Info field in *Staff → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: staff.default.primary.staff_info[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  staff_info: prismic.GroupField<
    Simplify<StaffSliceDefaultPrimaryStaffInfoItem>
  >;
}

/**
 * Default variation for Staff Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StaffSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StaffSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Staff*
 */
type StaffSliceVariation = StaffSliceDefault;

/**
 * Staff Shared Slice
 *
 * - **API ID**: `staff`
 * - **Description**: Staff
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StaffSlice = prismic.SharedSlice<"staff", StaffSliceVariation>;

/**
 * Item in *Videos → Default → Primary → Video*
 */
export interface VideosSliceDefaultPrimaryVideoItem {
  /**
   * Video field in *Videos → Default → Primary → Video*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: videos.default.primary.video[].video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.ContentRelationshipField<"video">;
}

/**
 * Primary content in *Videos → Default → Primary*
 */
export interface VideosSliceDefaultPrimary {
  /**
   * Video field in *Videos → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: videos.default.primary.video[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  video: prismic.GroupField<Simplify<VideosSliceDefaultPrimaryVideoItem>>;

  /**
   * Heading field in *Videos → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: videos.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * body field in *Videos → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: videos.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for Videos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Videos*
 */
type VideosSliceVariation = VideosSliceDefault;

/**
 * Videos Shared Slice
 *
 * - **API ID**: `videos`
 * - **Description**: Videos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideosSlice = prismic.SharedSlice<"videos", VideosSliceVariation>;

/**
 * Primary content in *WatchVideo → Default → Primary*
 */
export interface WatchVideoSliceDefaultPrimary {
  /**
   * Video Title field in *WatchVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: watch_video.default.primary.video_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_title: prismic.KeyTextField;

  /**
   * Video Description field in *WatchVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: watch_video.default.primary.video_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_description: prismic.KeyTextField;

  /**
   * Video field in *WatchVideo → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: watch_video.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video: prismic.EmbedField;

  /**
   * Video Upload field in *WatchVideo → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: watch_video.default.primary.video_upload
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_upload: prismic.LinkToMediaField;
}

/**
 * Default variation for WatchVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WatchVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WatchVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WatchVideo*
 */
type WatchVideoSliceVariation = WatchVideoSliceDefault;

/**
 * WatchVideo Shared Slice
 *
 * - **API ID**: `watch_video`
 * - **Description**: WatchVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WatchVideoSlice = prismic.SharedSlice<
  "watch_video",
  WatchVideoSliceVariation
>;

/**
 * Item in *WordList → Default → Primary → Words*
 */
export interface WordListSliceDefaultPrimaryWordsItem {
  /**
   * Word field in *WordList → Default → Primary → Words*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: word_list.default.primary.words[].word
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  word: prismic.KeyTextField;
}

/**
 * Primary content in *WordList → Default → Primary*
 */
export interface WordListSliceDefaultPrimary {
  /**
   * Words field in *WordList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: word_list.default.primary.words[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  words: prismic.GroupField<Simplify<WordListSliceDefaultPrimaryWordsItem>>;
}

/**
 * Default variation for WordList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WordListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WordListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WordList*
 */
type WordListSliceVariation = WordListSliceDefault;
type WordListSliceVariation = WordListSliceDefault;

/**
 * WordList Shared Slice
 *
 * - **API ID**: `word_list`
 * - **Description**: WordList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WordListSlice = prismic.SharedSlice<
  "word_list",
  WordListSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

<<<<<<< HEAD
  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProgramDocument,
      ProgramDocumentData,
      ProgramDocumentDataBoxItem,
      ProgramDocumentDataSlicesSlice,
      ProgrammenuDocument,
      ProgrammenuDocumentData,
      ProgrammenuDocumentDataNavigationItem,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      VideoDocument,
      VideoDocumentData,
      VideoDocumentDataSlicesSlice,
      VideoindexDocument,
      VideoindexDocumentData,
      VideoindexDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ProgramsSlice,
      ProgramsSliceDefaultPrimaryProgramsItem,
      ProgramsSliceDefaultPrimary,
      ProgramsSliceVariation,
      ProgramsSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      ShowCaseSlice,
      ShowCaseSliceDefaultPrimaryShowPieceItem,
      ShowCaseSliceDefaultPrimary,
      ShowCaseSliceVariation,
      ShowCaseSliceDefault,
      StaffSlice,
      StaffSliceDefaultPrimaryStaffInfoItem,
      StaffSliceDefaultPrimary,
      StaffSliceVariation,
      StaffSliceDefault,
      VideosSlice,
      VideosSliceDefaultPrimaryVideoItem,
      VideosSliceDefaultPrimary,
      VideosSliceVariation,
      VideosSliceDefault,
      WatchVideoSlice,
      WatchVideoSliceDefaultPrimary,
      WatchVideoSliceVariation,
      WatchVideoSliceDefault,
      WordListSlice,
      WordListSliceDefaultPrimaryWordsItem,
      WordListSliceDefaultPrimary,
      WordListSliceVariation,
      WordListSliceDefault,
    };
  }
=======
	namespace Content {
		export type {
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataNavigationItem,
			AllDocumentTypes,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			StaffSlice,
			StaffSliceDefaultPrimaryStaffInfoItem,
			StaffSliceDefaultPrimary,
			StaffSliceVariation,
			StaffSliceDefault,
			WordListSlice,
			WordListSliceDefaultPrimaryWordsItem,
			WordListSliceDefaultPrimary,
			WordListSliceVariation,
			WordListSliceDefault
		};
	}
>>>>>>> 0f71a22 (catch up)
}
